views.area.linkarea:
  type: views_area
  label: 'Link Area'
  mapping:
    tokenize:
      type: boolean
      label: 'Should replacement tokens be used from the first row'
    link_text:
      type: label
      label: 'The link text'
    path:
      type: string
      label: 'Link path'
    output_as_action:
      type: boolean
      label: 'Output as action'
    destination:
      type: boolean
      label: 'Include destination'
    external:
      type: boolean
      label: 'External'
    replace_spaces:
      type: boolean
      label: 'Replace spaces'
    absolute:
      type: boolean
      label: 'Use absolute path'
    path_case:
      type: string
      label: 'Transform the case'
    alt:
      type: label
      label: 'Title text'
    rel:
      type: string
      label: 'Rel Text'
    link_class:
      type: string
      label: 'Link class'
    prefix:
      type: label
      label: 'Prefix text'
    suffix:
      type: label
      label: 'Suffix text'
    target:
      type: string
      label: 'Target'
    rewrite_output:
      type: string
      label: 'Rewrite output'
    access_denied_text:
      type: string
      label: 'Access denied text'
    language:
      type: string
      label: 'Language'
